// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbZKXoUOvW2IB5_bIyZ65e8a4wxa3ayrg',
    appId: '1:77434630089:web:e762cc428983823c100218',
    messagingSenderId: '77434630089',
    projectId: 'kidsafe-breath-8368e',
    authDomain: 'kidsafe-breath-8368e.firebaseapp.com',
    storageBucket: 'kidsafe-breath-8368e.firebasestorage.app',
    measurementId: 'G-YCKBREJCNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM5_C1nBArY0JqjYJPtso6QRZpRvW67-k',
    appId: '1:77434630089:android:c4e39fb0132bd133100218',
    messagingSenderId: '77434630089',
    projectId: 'kidsafe-breath-8368e',
    storageBucket: 'kidsafe-breath-8368e.firebasestorage.app',
  );
}
